# Generated by Django 3.2.7 on 2023-10-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20231007_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='name',
        ),
    ]
